version: "3.8"

services:
  app:
    container_name: spotter-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file: .env.production
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: always
